### ISSUE TITLE
wrong :    sudo apt-add-repository ppa:ansible/ansible -y 

### ISSUE THREAD

**Issue by ningjianghang** [CumulusNetworks/cldemo-roh-ansible#1]
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 60, in <module>
    sp = SoftwareProperties()   
  File "/usr/lib/python2.6/dist-packages/softwareproperties/SoftwareProperties.py", line 90, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python2.6/dist-packages/softwareproperties/SoftwareProperties.py", line 538, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python2.6/dist-packages/aptsources/distro.py", line 90, in get_sources
    raise NoDistroTemplateException("Error: could not find a "
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template

**Comment by isharacomix** [comment]
Hi! The line ` sudo apt-add-repository ppa:ansible/ansible -y`  is no longer necessary. The readme has been updated to reflect this.
